In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


一

In [4]:
import numpy as np
arr = np.arange(1, 13)
arr_2d = arr.reshape(3, 4)
print("数组的维度 (ndim):", arr_2d.ndim)
print("数组的形状 (shape):", arr_2d.shape)
print("数组的元素总个数 (size):", arr_2d.size)


数组的维度 (ndim): 2
数组的形状 (shape): (3, 4)
数组的元素总个数 (size): 12


二

In [5]:
import numpy as np
arr_float=np.array([1.5, 2.6, 3.7, 4.8])
arr_int = arr_float.astype(np.int32)
print("转换前的数组:", arr_float)
print("转换前的数据类型:", arr_float.dtype.name)
print("转换后的数组:", arr_int)
print("转换后的数据类型:", arr_int.dtype.name)

      

转换前的数组: [1.5 2.6 3.7 4.8]
转换前的数据类型: float64
转换后的数组: [1 2 3 4]
转换后的数据类型: int32


三

In [6]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sub_arr = arr[:2, 1:3]
print("切片后的子数组:\n", sub_arr)


切片后的子数组:
 [[2 3]
 [6 7]]


四

In [7]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
fancy_result = arr[[0, 2, 4]]
bool_result = arr[arr > 20]
print("1. 花式索引结果:", fancy_result)
print("2. 布尔索引结果:", bool_result)


1. 花式索引结果: [10 20 30]
2. 布尔索引结果: [25 30 35]


arrb+2

In [ ]:
arr_b+2

NameError: name 'arr_b' is not defined

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Read timed out. (read timeout=9.15)")': /pkgs/msys2/noarch/repodata.json.zst



==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.0

Please update conda by running

    $ conda update -n base -c defaults conda




3 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
 - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
 - defaults
Platform: win-64
Solving environment: done

## Package Plan ##

  environment location: d:\minicoda\envs\huanjingname

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bottleneck-1.4.2           |  py310h540bb41_1         121 KB  https://mirrors.ustc.edu.cn/anaconda/pkgs/main
    libiconv-1.18              |       hc89ec93_0         687 KB  https://mirrors.ustc.edu.cn/anaconda/pkgs/main
    libxml2-2.13.9             |       h6201b9f_0         1.5 MB  https://mirrors.ustc.edu.cn/anaconda/pkgs/main
    mkl-service-2.5.2          |  py310h0b37514_0          72 KB  https://mirrors.ustc.edu.cn/anaconda/pkgs/main
    mkl_fft-2.2.0              |  py310h18b77b3_0         153 

In [ ]:
import numpy as np
arr_zeros = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_zeros + arr_b
print("全0数组:\n", arr_zeros)
print("\n一维数组:", arr_b)
print("\n相加后的结果:\n", result)


全0数组:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

一维数组: [1 2 3 4]

相加后的结果:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


六

In [ ]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
sqrt_result = np.sqrt(x)
max_result = np.maximum(sqrt_result, y)
print("1. 平方根数组:", sqrt_result)
print("2. 对应位置的最大值:", max_result)


1. 平方根数组: [1. 2. 3. 4.]
2. 对应位置的最大值: [2. 2. 4. 5.]


七

In [ ]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
transposed_arr = arr.transpose((1, 0, 2))
print("原数组形状:", arr.shape)
print("转置后数组的形状:", transposed_arr.shape)


原数组形状: (2, 3, 4)
转置后数组的形状: (3, 2, 4)


八

In [ ]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
result = np.where(arr_con, arr_x, arr_y)
print("条件逻辑运算结果:", result)



条件逻辑运算结果: [1 6 7]


九

In [ ]:
import numpy as np
arr = np.array([[6, 2, 7], 
                [3, 6, 2], 
                [4, 3, 2]])
mean_value = np.mean(arr)
print("1. 数组所有元素的算术平均值:", mean_value)
sorted_arr = np.sort(arr, axis=0) 
print("2. 按列排序后的结果:")
print(sorted_arr)


1. 数组所有元素的算术平均值: 3.888888888888889
2. 按列排序后的结果:
[[3 2 2]
 [4 3 2]
 [6 6 7]]


In [ ]:
row_mean=np.mean(arr,axis=1)
print(row_mean)

[5.         3.66666667 3.        ]


十

In [ ]:
import numpy as np
np.random.seed(10)
A = np.random.random((2, 2))
B = np.random.random((2, 2))
dot_product = np.dot(A, B)
print("矩阵A：\n", A)
print("矩阵B：\n", B)
print("点积结果：\n", dot_product)


矩阵A：
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
点积结果：
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]


In [ ]:
conda install pandas


^C

Note: you may need to restart the kernel to use updated packages.
